trigger:
    branches:
        include:
            - '*'
    tags:
        include:
            - '*'

resources:
    containers:
        - container: rust
          image: rust:latest
        - container: tarpaulin
          image: xd009642/tarpaulin:latest-nightly
          options: --security-opt seccomp=unconfined

jobs:
    - job: Test
      pool:
          vmImage: 'ubuntu-16.04'
      container: rust
      steps:
          - script: |
              cargo test
            displayName: Run test

    - job: Coverage
      pool:
          vmImage: 'ubuntu-16.04'
      container: tarpaulin
      steps:
          - script: |
              cargo tarpaulin -v --out Xml
              curl -s https://codecov.io/bash -o .codecov && chmod +x .codecov
              ./.codecov -B "${BUILD_SOURCEBRANCHNAME:-}" \
                         -C "${BUILD_SOURCEVERSION:-}" \
                         -P "${SYSTEM_PULLREQUEST_PULLREQUESTNUMBER:-}" \
                         -b "${BUILD_BUILDID:-}" \
                         -K -n "report name"
            displayName: Run tarpaulin
            env:
                CODECOV_TOKEN: $(CODECOV_TOKEN)
